export const initialData = {
  head: {
    name: "Name",
    favoriteFood: "Favorite Food",
    favoriteColor: "Favorite Color",
    numberOfPets: "Total # of Pets",
    dob: "Birthday",
  },
  body: [
    {
      name: "Barbara Lopez",
      favoriteFood: "Hamburger",
      favoriteColor: "White",
      numberOfPets: 3,
      dob: "1991-04-18",
    },
    {
      name: "Isaac Robbins",
      favoriteFood: "Wonton soup",
      favoriteColor: "Yellow",
      numberOfPets: 3,
      dob: "1969-08-31",
    },
    {
      name: "Dorothy Reeves",
      favoriteFood: "Seaweed salad",
      favoriteColor: "Purple",
      numberOfPets: 3,
      dob: "1987-12-17",
    },
    {
      name: "Corey Ball",
      favoriteFood: "Sweet potato fries",
      favoriteColor: "Pink",
      numberOfPets: 4,
      dob: "2002-12-24",
    },
    {
      name: "Rosie Pena",
      favoriteFood: "Salmon avocado roll",
      favoriteColor: "Brown",
      numberOfPets: 2,
      dob: "1963-03-14",
    },
    {
      name: "Linnie Benson",
      favoriteFood: "Sweet potato fries",
      favoriteColor: "Orange",
      numberOfPets: 2,
      dob: "1985-01-05",
    },
    {
      name: "Edwin Hines",
      favoriteFood: "Cheesy fiesta potatoes",
      favoriteColor: "Pink",
      numberOfPets: 2,
      dob: "1998-04-28",
    },
    {
      name: "Javier Marshall",
      favoriteFood: "Pepperoni pizza",
      favoriteColor: "Red",
      numberOfPets: 1,
      dob: "1995-07-09",
    },
    {
      name: "Sophie Walker",
      favoriteFood: "Chicken tacos",
      favoriteColor: "Blue",
      numberOfPets: 0,
      dob: "2000-11-25",
    },
    {
      name: "Mason Clarke",
      favoriteFood: "Pasta carbonara",
      favoriteColor: "Green",
      numberOfPets: 2,
      dob: "1983-06-02",
    },
    {
      name: "Eleanor Rose",
      favoriteFood: "Mango sticky rice",
      favoriteColor: "Teal",
      numberOfPets: 5,
      dob: "1974-09-30",
    },
    {
      name: "Dylan Ford",
      favoriteFood: "Steak and mashed potatoes",
      favoriteColor: "Black",
      numberOfPets: 1,
      dob: "1992-03-15",
    },
    {
      name: "Nina Caldwell",
      favoriteFood: "Caesar salad",
      favoriteColor: "Gold",
      numberOfPets: 3,
      dob: "1980-12-05",
    },
    {
      name: "Oliver Bennett",
      favoriteFood: "Lobster roll",
      favoriteColor: "Navy",
      numberOfPets: 2,
      dob: "1967-05-19",
    },
    {
      name: "Lucas Hayes",
      favoriteFood: "Chocolate lava cake",
      favoriteColor: "Silver",
      numberOfPets: 4,
      dob: "1999-08-14",
    },
    {
      name: "Madeline Russell",
      favoriteFood: "Avocado toast",
      favoriteColor: "Lavender",
      numberOfPets: 0,
      dob: "2005-10-07",
    },
    {
      name: "Ethan Carter",
      favoriteFood: "BBQ ribs",
      favoriteColor: "Maroon",
      numberOfPets: 1,
      dob: "1979-02-23",
    },
    {
      name: "Grace Mitchell",
      favoriteFood: "Butter chicken",
      favoriteColor: "Turquoise",
      numberOfPets: 2,
      dob: "1996-11-11",
    },
    {
      name: "Henry Foster",
      favoriteFood: "Pho",
      favoriteColor: "Olive",
      numberOfPets: 3,
      dob: "1988-04-29",
    },
    {
      name: "Charlotte Simmons",
      favoriteFood: "Shrimp scampi",
      favoriteColor: "Coral",
      numberOfPets: 2,
      dob: "2001-07-03",
    },
  ],
};
